lexik_jwt_authentication:
    secret_key: "%env(resolve:JWT_SECRET_KEY)%"
    public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
    pass_phrase: "%env(JWT_PASSPHRASE)%"
    token_ttl: 14400

    token_extractors:
        cookie:
            enabled: true
            name: BEARER

    set_cookies:
        BEARER: ~
