knp_gaufrette:
    stream_wrapper: ~

    adapters:
        marque_adapter:
            local:
                directory: "%kernel.project_dir%/public/images/marques"
        model_adapter:
            local:
                directory: "%kernel.project_dir%/public/images/models"
        product_adapter:
            local:
                directory: "%kernel.project_dir%/public/images/products"

    filesystems:
        marque_fs:
            adapter: marque_adapter
        model_fs:
            adapter: model_adapter
        product_fs:
            adapter: product_adapter

vich_uploader:
    db_driver: orm
    storage: gaufrette

    metadata:
        type: attribute

    mappings:
        marques:
            uri_prefix: /images/marques
            upload_destination: marque_fs
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true

        models:
            uri_prefix: /images/models
            upload_destination: model_fs
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true

        products:
            uri_prefix: /images/products
            upload_destination: product_fs
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true
